### PR TITLE
Do not fail on unknown properties.

### PR DESCRIPTION
**Pull request by bgiori**
Updates the CBOR ObjectMapper to not fail on unknown properties.

This change hopefully prepares the library for a larger scale update with regards to documenting the protocol and enforcing protocol version.

### CODE REVIEW

**Comment by philips77** [comment]
I updated this branch so it can be merged. But please, verify. The test proposed also was passing for me on master, and it's not clear what does it test.

**Comment by ebabel** [comment]
> I updated this branch so it can be merged. But please, verify. The test proposed also was passing for me on master, and it's not clear what does it test.

Thanks, it's been a while but I guess the 'test' was more just a demonstration of something breaking. Would be nice having a test marshalling a complex 'real-world' object (McuMgrImageStateResponse ) instead of simple java types.

**Comment by bgiori** [comment]
Yeah, this is stale. Closing.

**Comment by ebabel** [comment]
It's coming back to me, I think I was saying that the 'test' I wrote successfully demonstrated that this branch can create a McuMgrImageStateResponse.ImageSlot without all of the properties populated whereas master (pre-merged) cannot.

**Pull request closed without merging**
