### PR TITLE
Speed and reliablity improvements

### PR DESCRIPTION
**Pull request by philips77**
This PR, although not compatible with 2 other pending PRs, adds some minor improvements:
1. Adds a method to `McuMgrBleTransport` to request connection priority. This may improve speed. I didn't request the priority in `initialize()` as this may not be required.
2. Adds 2 retry attempts to to connect to the device after it was rebooted. On nRF85840 the swap operation takes ~30 seconds and some phones may not pick up the adv interval in remaining time (if there is any). Issue found on Samsung Note 8 when adv interval is 1 second.
3. Null checks

### CODE REVIEW

**Comment by philips77** [comment]
I've added an option to set the estimated swapping time. The lib will start reconnecting only after the time finishes. Perhaps some progress/other state?

**Comment by bgiori** [comment]
I just looked it up and wanted to correct myself: latest android versions (8+) have reduced the supervision timeout from 20 seconds to 5 seconds. 

To clarify, an example:

Let's say the user is running Android 7 (20 second supervision timeout) and the board is an nRF85840. The developer has set the expected swap time to 30 seconds.

In this case, the `verify()` will be posted 30 seconds after the disconnect, which will get received 20 seconds after the reset command is sent. Therefore the effective wait time between RESET & CONFIRM is 50 seconds (not 30 seconds).  

On the other hand, if the user is running Android 8 (5 second supervision timeout) and expected swap time remains constant (30 seconds), then the effective wait time between RESET & CONFIRM would be 35 seconds.

This difference may be confusing to developers and users alike. If the developer tests the firmware upgrade with their device on Android 7, and modifies the expected swap time accordingly, then a user running android 8 may see consistent failures due to the 15 second difference in the supervision timeout.


In my opinion, the solution may be to normalize the expected swap time based on the android version. So for android 7, if the developer sets and expected swap time of 30 seconds it would be normalized to 10 to account for the 20 second supervision timeout. For Android 8 it would be normalized to 25 seconds to account for the 5 second supervision timeout.

If you think normalization is even more confusing, then I'm fine with keeping it out too. I just want to consider the implications.

**Comment by philips77** [comment]
Well... As far as I know, the change 20->5 was made few days ago, not in Android 8. Besides, a different value may be requested from peripheral side, so there's no guarantee that this 20 sec is the current value. On 8+ there is onConnectionUpdated callback, so this value is known, but before 8 it is not.
Also, supervision timeout doesn't matter if a graceful disconnect was made. I'm pretty sure that Zephyr replies response to reset command and then sends disconnect before restarting, at least whenever I tested that was super quick. Don't know how Mynewt. If it doesn't, I thing it should be fixed there, not on Android side.
Then the delay is only required for the swap phase.

**Comment by philips77** [comment]
Patch that decreased supervision timeout 20->5 sec: https://android-review.googlesource.com/c/platform/packages/apps/Bluetooth/+/355840 
Related issue: https://issuetracker.google.com/issues/37074926

**Pull request merged**
