### PR TITLE
Migration to BLE library 2.2.0

### PR DESCRIPTION
**Pull request by philips77**
This PR migrates the *mcumgr-ble* component to BLE Library 2.2.0. Currently this is in alpha stage, but very close to release. I will add another commit to this PR when the final release is complete. So far, after testing the sample app, I did not find any issues.

### CODE REVIEW

**Comment by bgiori** [comment]
I will let you do the final merge at your convenience, at which point I will build a release.

**Comment by philips77** [comment]
a
b
c
e
f

**Comment by philips77** [comment]
Ready to be released!

**Comment by philips77** [comment]
Hmm.. i think I forgot to set Apache license in new files. Could you check them?

**Comment by bgiori** [comment]
Sure, I will add them.

**Comment by bgiori** [comment]
https://github.com/JuulLabs-OSS/mcumgr-android/commit/57d72c533b5b7c17a73b4ae7cdc67225642b2136

I think thats all of them from this PR.

**Pull request merged**
